kaitai-io/kaitai_struct_formats

network/udp_datagram.ksy

https://www.ietf.org/rfc/rfc768.txt

Add UDP Datagram as specified in rfc768

---

game/quake_mdl.ksy

As promised, if a little late.
String terminator on line 125 is commented out for now, waiting on kaitai-io/kaitai_struct#13.

Add Quake MDL format

---

serialization/bson.ksy

and here are [some test files](https://github.com/kaitai-io/kaitai_struct_formats/files/748959) for @koczkatamas's IDE

Added ksy for BSON

---

geospatial/shapefile_index.ksy
geospatial/shapefile_main.ksy

Source: https://www.esri.com/library/whitepapers/pdfs/shapefile.pdf

Add Shapefile main (.shp) and index (.shx) formats

---

archive/cpio_old_le.ksy

Source: https://people.freebsd.org/~kientzle/libarchive/man/cpio.5.txt

Add cpio archive, old binary variant, little-endian

---

scientific/spectroscopy/avantes_roh60.ksy

Added the support for Avantes spectrometers as advertised before in https://github.com/kaitai-io/kaitai_struct/issues/160#event-1067351175

Avantes spectral format 6.0

---

scientific/spectroscopy/avantes_roh60.ksy

simplified the file structure as suggested by GreyCat https://github.com/kaitai-io/kaitai_struct_formats/pull/35#discussion_r114602220

simplified the file structure

---

image/dicom/dicom_common.ksy
image/dicom/dicom_le_explicit.ksy
image/dicom/dicom_le_generic.ksy
image/dicom/dicom_le_implicit.ksy
image/dicom_le.ksy

Hi there,
I am not sure this grammar does not cover all cases, but was working for all my datasets. At elast in he WebIDE.

Added format image/dicom_le.ksy

---

network/tls_client_hello.ksy

This PR adds a TLS client hello parser

Added TLS client hello parser

---

game/saints_row_2_vpp_pc.ksy

Yet another game container reversed by yours truly. Not a VN, probably should be safe. KaitaiFS implementation would be also underway.

Added Saints Row 2 package file format

---

filesystem/lvm2.ksy

Added lvm2

---

common/vlq_base128_be.ksy
common/vlq_base128_le.ksy

Small update to doc, picking words.

VarInt doc updated

---

filesystem/apm_partition_table.ksy

Was tested on multi structure CD ( ISO9660 + APM ) and APM created with parted.
I have no access to an old Apple HDD at this point.

APM (Apple Partition Map) partition table

---

executable/microsoft_pe.ksy

This is limited to support for the coff symbols that I happened to come across.
It does support:
- symbol names (both short and long)
- looking up section + value to get the actual value
It does not support:
- types -- all symbols in my file are type 0
- storage classes -- all symbols in my file are storage class 2 or 3.  (extern or static)
- aux symbols -- none of mine had any

Add partial support for coff symbols

---

executable/dex.ksy

- replaced partially incorrect implementation of uleb128
- added more human-readable fields for certain sections

Improved DEX format

---

executable/elf.ksy
executable/mach_o.ksy

- Mach-O: fixes a flag-type field representation (`macho_flags`)
- ELF: parses phdr_type & section_header flags
- ELF: parses dynamic section

ELF + Mach-O update

---

executable/elf.ksy

This isn't perfect as you need to manually look up the symbol names in dynstr,
but it's a step in the right direction.

elf: skeleton dynsym/dynstr support

---

executable/microsoft_pe.ksy

https://msdn.microsoft.com/en-us/library/windows/desktop/ms680547(v=vs.85).aspx#Windows_Subsystem

microsoft_pe.ksy - Update SubSystem Enum

---

media/gettext_mo.ksy

For how it doesn't work because of the bug in the compiler. If I replaced endianness selection logic with `le`, it works.

Added gettext mo

---

firmware/uimage.ksy
network/protocol_body.ksy

couple edits to get all .ksy's to compile

minor fixes: uimage, protocol_body

---

network/bitcoin_transaction.ksy

Hello,
I would like to apply what I've learnt from #131 to #102.
This PR brings the following improvements:
* Change the license (see https://github.com/kaitai-io/kaitai_struct_formats/pull/131#discussion_r273331680)
* Nest types and enumerations into others when it's relevant
* Use `len` as a prefix and not as a suffix as defined in the [style guide](https://doc.kaitai.io/ksy_style_guide.html#attr-id).
Thanks

Improve bitcoin transaction

---

media/stl.ksy

(https://github.com/kaitai-io/kaitai_struct/issues/612)
I haven't figured out how to test this change yet, so please take this PR with a grain of salt. Some instructions (perhaps in a BUILDING.txt) for how to do a full build of your project prior to PR's would be helpful. If I've missed it in the docs sorry... all I see is lots about how to run from binaries, and not much about how to build the project and run whatever test suites you have.

Potential fix for issue #612 - Buffer Underflow Exception

---

media/android_opengl_shaders_cache.ksy

Added com.android.opengl.shaders_cache

---

archive/android_img.ksy

docs: https://source.android.com/devices/bootloader/boot-image-header
google implementation: https://android.googlesource.com/platform/system/core/+/refs/heads/android10-c2f2-release/mkbootimg/unpack_bootimg.py#45
Signed-off-by: Denis Efremov <efremov@linux.com>

Add android boot image format

---

_build/build-html
_build/format_base.html.erb
_build/format_lang.html.erb
_build/usage_cpp_stl.html.erb
_build/usage_csharp.html.erb
_build/usage_java.html.erb
_build/usage_javascript.html.erb
_build/usage_python.html.erb
_build/usage_ruby.html.erb

See https://github.com/kaitai-io/kaitai_struct_formats/pull/278

Syntax highlighting of language-specific usage code snippets

---

_build/header.html.erb

as per https://github.com/kaitai-io/kaitai-io.github.io/pull/12

Remove REPL link

---

network/dns_packet.ksy

Add type AAAA, and change definition of IP from list of u2 to byte array.

network/dns_packet.ksy: Add IPv6 and make IP/v6 definition more clear

---

_build/.gitignore
_build/format_xref.html.erb

Fixes u4 -> u1 for unicodestring1 op
Fixes typo in id reference.

Fixes errors in python pickle format

---

media/magicavoxel_vox.ksy

Found this during testing of my [parser](https://github.com/Mingun/ksc-rs). Fixes #281

Fix incorrect use of doc-ref

---

executable/swf.ksy

Fix misprint if SWF xref location

---

firmware/broadcom_trx.ksy

Renamed asus_trx to broadcom_trx

---

image/icc_4.ksy

http://www.color.org/registry/signature/TagRegistry-2021-03.pdf

ICC: sync CMS Signatures with latest CMM signature registry

---

executable/elf.ksy

Add ET_NONE type, plus a few machine types. I have seen most of these in real life, and recently.

ELF: add ET_NONE, add several more machine types, ELF fixes

---

media/au.ksy

a simple parser for the AU audio format. The contents of the streams themselves are not parsed.

add AU (Sun/NeXT audio)

---

archive/android_sparse.ksy

This commit adds a description of the Android sparse file format.

add Android sparse format

---

archive/rpm.ksy

rpm: add RPMTAG_ARCHSUFFIX tag

---

log/mcap.ksy

Hi! This PR imports the KSY definition for MCAP from: https://github.com/foxglove/mcap/pull/308 
This is my first time using KSY; I tried to conform to the style guide but please let me know if you have any feedback on the definition.
More info on the MCAP format: https://github.com/foxglove/mcap#readme
Example data:
- Simple examples: https://github.com/foxglove/mcap/tree/main/tests/conformance/data
- To generate more complex example data, use the [`mcap convert` tool](https://github.com/foxglove/mcap/tree/main/go/cli/mcap) on a ROS Bag file, e.g. the files from https://google-cartographer-ros.readthedocs.io/en/latest/data.html

Add log/mcap.ksy

---

database/dbf.ksy

More flexible and detailed dbf file parser/analyser. Do not tested on ksc - only in Web IDE

Fix dbf.ksy

---

executable/mach_o.ksy

See specific commit messages for details. These are all bugfixes and trivial features.
This contribution is on behalf of my company, unlike my prior ones. I will note when the case for this and all future PRs.

Various Mach-O fixes

---

network/pcap.ksy

This PR adds a new link type (299).

pcap: add new link type
