kaitai-io/kaitai_struct_formats

filesystem/cramfs.ksy

For now, with compressed blocks as `size-eof: true` field until iterator access or another mechanism that allows parsing this data becomes available.

Add CramFS format

---

network/dns_frame.ksy

Isn't a complete implementation but should support the average DNS record. 
Notable features this sample highlights are:
- How to currently work with bitfields and bitflags
- How to use repeat-expr
- Self-offsetted instances using types
The following improvements to Kaitai would really help:
- Fix to the fact you can't really use any non-alpha char in enum values (even in quotes)
- Meta should really have a doc tag (already in the works I see)
- Bitflags to help avoid hacks (also in the works)
- The ability to have an OR in an if statement (to avoid hack-fixes)
- Hierarchical parsing of data with multiple ksy files (to allow for a full packet rather than just the DNS payload)
- Better doc (I plan to cover this)

Added initial DNS implementation

---

network/dns_packet.ksy

- Comment used rather than application
- Flags instance used rather than enum
- Updated docs and ids to align with RFC rather than guesswork
- Added unit to ttl
- Added support for A-class records now I've found more samples
- Updated expressions to use newly discovered "or" function and instanced fields for clarity
- Removed dead code
- Dequoted enum-values based upon feedback (needed to leave null given it causes problems otherwise as a literal)

Improvements based upon feedback (see description)

---

firmware/andes_firmware.ksy

Add a `firmware` directory and a firmware image format for an obscure platform.
I can see there being many `firmware` image formats and I think these are distinct from `executable` formats which already have a directory. 
The format specified here is enough to parse out a firmware image for use with driver development, but it misses the bit fields that encode the firmware version. The correct way to do this is [documented in a blog post here][1], it is just a simple bit mask:
print("fw version: {}.{}.{}"
.format(
(fw_ver & 0xf000) >> 8,
(fw_ver & 0x0f00) >> 8,
fw_ver & 0x00ff))
I am not sure how to implement this and I am not entirely sure it is required.
There are also firmware images with the documented header used as a format trailer. The code I have currently tries to parse the …

Add binary image lay for andes firmware found in mediatek 76x0U devices

---

image/icc_4.ksy

Specification for profile version 4.3.0.0:
http://www.color.org/specification/ICC1v43_2010-12.pdf
Tested against sample version 4.* profiles available at:
https://bugzilla.mozilla.org/show_bug.cgi?id=488800
This script adds support for most ICC-defined tag types, however in some
cases the support provided is basic. Some further improvements which
need to be made include:
- using enums for tags of type signature_type (split signature_type into
multiple independent types so they can each use a different enum)
- finish defining some of the more complex numerical/tabular tag types
This script will only parse version 4.* profiles even though previous
version 2.* profiles are quite similar in structure and can be partially
parsed using this script as well. Another improvement would be to create …

Add ICC profile, version 4

---

executable/java_class.ksy

This adds all the constant structures for `.class` files from https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html
I also reordered everything so it is in the same order as the description page. I also found a bug that probably cannot be fixed without an overhaul of kaitai struct itself but I will open a separate issue for that. For now this is definitely an improvement over the previous version that wouldn't even accept the most basic class files.

added additional constant structures

---

media/id3v2_3.ksy
media/id3v2_4.ksy

This does not include the specifications for each of the frames because that would be overkill (just too many of them, each with many quirks), but their data can be accessible as raw bytes.
More information about frames:
* ID3v2.3.0 frames: http://id3.org/id3v2.3.0#Declared_ID3v2_frames
* ID3v2.4.0 frames: http://id3.org/id3v2.4.0-frames
Everything else works exactly as expected. One minor remark is that since the standard does not require specifying how many frames are there (or how long the padding is), the only way of recognizing the last frame is reading the 4-bytes afterwards and comparing against `\x00\x00\x00\x00`. This creates a *NULL*-frame with some MP3 files. However, this behavior occurs in all audio players as well.

Added ID3v2.3.0 and ID3v2.4.0 specifications

---

game/gran_turismo_vol.ksy

So, this is clearly not VNs, I hope you'll accept that into main repo.
Tested on GT2, probably should work on GT1 as well. And, yeah, I've even managed to not forget to add the `meta/license` tag ;)
All reverse engineering is my own work. I might do KaitaiFS module for this later.

Added Gran Turismo GTFS .vol files support

---

image/png.ksy

If there are extra bytes at the end of the PNG (e.g. if the PNG is embedded in some other sort of file), the parser will try to read in new chunks even if they're nonsensical, and will often fail because of
invalid data in the garbage chunk (like a "chunk size" larger than the file) By stopping at the IEND chunk, the parser won't keep trying to read more chunks past the end of the file.

Stop reading PNGs after the IEND chunk

---

game/fallout2_dat.ksy
game/fallout_dat.ksy

As in the title, these format descriptions are for the .dat archives in Fallout1 and Fallout2 games.
Note that Fallout1 archive use a custom LZSS compression algorithm that requires additional code for decompression.

Add Fallout1 and Fallout2 .dat file formats

---

network/tls_client_hello.ksy

Removes a redundant type in tls client hello parser
Earlier -
```
for cs in cipher_suites.cipher_suites:
print(cs.cipher_suite)
```
Now -
```
for cs in cipher_suites.cipher_suites:
print(cs)
```

Removed redundant type

---

media/wav.ksy

This ksy file supports PCMWAVEFORMAT, WAVEFORMATEX and WAVEFORMATEXTENSIBLE subtypes, which means it should work for multiple channel and other esoteric formats.  It gives special consideration to fmt, data, bext, and cue chunks, which have specific meaning to the Microsoft format.

Initial support for Microsoft WAV audio files

---

executable/mach_o.ksy

As per discussion on issue 222 on the main repository (https://github.com/kaitai-io/kaitai_struct/issues/222).

mach_o.ksy: Provide bitmask-like access to vm_prot by using a bX-based declaration

---

executable/mach_o.ksy

This pull request aims at providing the following changes:
- Add support for arm64 cpu type
- Fix handling of `LC_MAIN` load command
- Fix `load_upward_dylib` load command type
- Add support and handle most of the missing commands, adding the declarations of the struct they represent where necessary:
- `LC_ROUTINES`
- `LC_ENCRYPTION_INFO` and `LC_ENCRYPTION_INFO_64`
- `LC_SEGMENT_SPLIT_INFO`
- `LC_ROUTINES_64`
- `LC_SUB_FRAMEWORK`, `LC_SUB_CLIENT`, `LC_SUB_UMBRELLA` and `LC_SUB_LIBRARY`
- `LC_LINKER_OPTION`
- `LC_TWOLEVEL_HINTS`
- `LC_ID_DYLINKER`
- `LC_DYLD_ENVIRONMENT`
- `LC_DYLIB_CODE_SIGN_DRS`
- `LC_VERSION_MIN_{IPHONEOS,TVOS,WATCHOS}`
Please, let me know if the declaration needs to be improved with regards to style conventions or other factors. I would be happy to make any change, if …

Extend and improve support for the Mach-O file format

---

executable/mach_o.ksy

As discussed in https://github.com/kaitai-io/kaitai_struct_formats/pull/50, this pull request applies the required style changes and adds `-orig-id` to some members of the declaration.

mach_o.ksy: Fix styling issues and add -orig-id

---

firmware/ines.ksy

- Removed `meta/endian`: The specification doesn't define an endianness and doesn't require one
- Removed `ines` file extension: The specification only defines `.nes` as a valid file extension
- This is debatable, even though the spec doesn't define it, it may be useful to define in the KSY file anyway
- Renamed a few fields for clarity
- Added enums for b1 types that don't fit true/false
- Added missing fields for the body of the ROM file
A collection of test ROMs can be found at https://wiki.nesdev.com/w/index.php/Emulator_tests. These tests are designed for emulator implementations, however they can also be used to test just the file format.

Updated iNES format

---

game/heaps_pak.ksy

Added spec for the PAK format used by the Haxe Game framework [Heaps](http://heaps.io) which is used by is used by the indie game [Dead Cells](https://dead-cells.com), allowing parsing and dumping the game's resources (stored in "res.pak"):
Let me know if something is amiss or needs more work for this pull request to be accepted.

Added PAK format used by Dead Cells game

---

executable/elf.ksy

This is used by the PaX Linux security patch.  Verification can be seen at
https://pax.grsecurity.net/binutils-2.16-pt-pax-flags-200506102235.patch:
+#define PT_PAX_FLAGS	(PT_LOOS + 0x5041580) /* PaX flags */

executable/elf: add missing PAX_FLAGS segment type

---

image/gif.ksy

This PR makes the gif parser read GIFs only till EOF block. This prevents parsing errors in case a file has bytes after the EOF block.
[example gif](https://user-images.githubusercontent.com/16747982/34779270-b86ca25e-f645-11e7-80e0-1624e90ea0fb.gif)

Read GIFs till EOF block

---

media/magicavoxel_vox.ksy

Tested with a voxel model with MATT chunks from https://blog.sketchfab.com/complete-guide-importing-magicavoxel-sketchfab/.
Actual test file can be downloaded here: https://www.cyn-prod.com/files/lab_vox.zip (CC-BY license https://sketchfab.com/elbriga).
Other test files can be found in the MagicaVoxel download for Windows or MacOS (https://ephtracy.github.io/).
Generated C# code for testing the runtime and it all seems to work fine. 
I plan to replace my own .vox read (and eventually writing) code with this in https://github.com/Arlorean/Voxels.

Added MagicaVoxel .vox file specification

---

filesystem/gpt_partition_table.ksy

It works on 512 byte sector size only.

GPT partition table parser, will process primairy and backup sets

---

network/icmp_packet.ksy

The ICMP echo messages are missing the final data field. The size information is in the IP header, so we just read until the end of the substream.
Thanks again for the fantastic project! 🍰

[network/icmp_packet] add missing data field

---

executable/microsoft_pe.ksy

I was not sure where to put `certificate_table` exactly, so I put under `pe` as an instance.

PE: add certificate table parsing

---

executable/microsoft_pe.ksy

The annoyingstring is annoying but we do not need all there members (only one of them which we use it in the "name" field)...

remove redundant fileds - annoyingstring

---

network/bitcoin_transaction.ksy

Hi,
This PR contains a KSY file for decoding raw Bitcoin transactions (see an [example](https://github.com/kaitai-io/kaitai_struct_formats/files/2503578/raw_bitcoin_transaction.zip)).
Cheers

Add bitcoin transaction

---

README.md

Style guide is hard to discover, there's no link to it anywhere.
I'm not sure if I used correct grammar.

Add link to style guide to readme

---

filesystem/trd.ksy

[TR-DOS](https://en.wikipedia.org/wiki/TR-DOS) is operating system for ZX-Spectrum computer with Beta Disc floppy drive interface. It might be not very popular in the west, but was especially popular in USSR and early post-USSR due to availability of Soviet clones of Beta Disc and WD1793.
`.trd` files are sector-by-sector raw floppy disk dumps (similar to PC floppy `.img` or copies of `/dev/fd0`), so this format file describes actual TR-DOS filesystem rather than `.trd` format itself.
~May not compile for `graphviz` and `go` right now due to https://github.com/kaitai-io/kaitai_struct/issues/491~ (removed `substring` because changed to bytes)

Add TR-DOS filesystem format

---

log/aix_utmp.ksy

Hi, I've added spec file for parsing IBM AIX utmp format.
Based on: https://www.ibm.com/support/knowledgecenter/en/ssw_aix_72/com.ibm.aix.files/utmp.h.htm

Added spec for parsing IBM AIX utmp format

---

serialization/asn1/asn1_der.ksy

There was already handling of two-byte lengths (`0x82`); extend the handling to include 1 byte lengths also (`0x81`)

asn1: handle also 1-byte lengths

---

image/exif_be.ksy
image/exif_le.ksy

Added missing field types in field_type_enum of exif files, which were missing according to the official spec: https://www.exif.org/Exif2-2.PDF. Addresses https://github.com/mitmproxy/mitmproxy/issues/3360#issue-373534204 .

Added missing exif field types

---

log/sudoers_ts.ksy

Hello,
After I read https://github.com/nongiach/sudo_inject, I was wondering whether the format of time stamp files used by `sudo` was implemented in Kaitai Struct. As it is not, here is a PR to add it.
This format is quite simple, it consists of a sequence of entries defined by `struct timestamp_entry` in `sudo`'s source code. This is similar to `utmp` files, which is why I created a format in `log/`.
As of today, there are two versions of this format:
* version 1 has only been "documented" in sudo's source code, https://www.sudo.ws/repos/sudo/file/SUDO_1_8_10/plugins/sudoers/check.h
* version 2 is officially documented on https://www.sudo.ws/man/1.8.27/sudoers_timestamp.man.html. Its main difference is the field `struct timespec start_time`, which have been introduced.
Could you please …

Add Sudoers Time Stamp file format

---

macos/ds_store.ksy

Hello,
This PR aims to add a description for the macOS `.DS_Store` files generated by the Finder. You can test the description on these files: [ds_store_samples.zip](https://github.com/kaitai-io/kaitai_struct_formats/files/3015783/ds_store_samples.zip)
There are two things I would like to improve though:
* The position of certain instances need to be calculated according to `alignment_header` but I didn't succeed to make it work. I had to manually add 4 to the result as in this example: `buddy_allocator_header.ofs_bookkeeping_info_block + 4`
* When I try to use `_index` lines 65 and 66, I get the following error: `undefined TypeError: this.directoryEntries[i] is undefined`. I think it is the same issue as described in https://github.com/kaitai-io/kaitai_struct/issues/436.
Could you please …

macOS '.DS_Store' files

---

security/efivar_signature_list.ksy

This new format parses UEFI variables `db` and `dbx` that contain signatures, certificates and hashes. On a Linux system using UEFI, these variables are readable from `/sys/firmware/efi/efivars/db-d719b2cb-3d3a-4596-a3bc-dad00e67656f`, `/sys/firmware/efi/efivars/dbDefault-8be4df61-93ca-11d2-aa0d-00e098032b8c`, `/sys/firmware/efi/efivars/dbx-d719b2cb-3d3a-4596-a3bc-dad00e67656f` and `/sys/firmware/efi/efivars/dbxDefault-8be4df61-93ca-11d2-aa0d-00e098032b8c`.
I added this new format in `security/`, next to OpenPGP message and SSH pubkey formats. If another directory is more suitable, this format can be moved.

Add UEFI db and dbx Signature List format

---

network/websocket.ksy

Should we add a CI check that just runs the compiler on every format when opening a PR? Should hopefully catch issues like this in the future.

network/websocket: Fix invalid `frame_header` ref

---

filesystem/zx_spectrum_tap.ksy

Contrary to what the file format spec describes the reserved field in a bytes block doesn't always contain 0x8000.

Support TAP files that don't have 0x8000 in bytes block reserved field

---

game/renderware_binary_stream.ksy

The versions listed in the documentation do not match the library stamp id in the chunk headers. Change the chunk header field to a more approriate name and introduce a version instance variable to make the checks work.

Fix version check in renderware_binary_stream.ksy

---

serialization/pickle.ksy
serialization/python_pickle.ksy

Add Python Pickle format

---

serialization/python_pickle.ksy

Contrary to every other data type in a Pickle, doubles are stored big endian [1]
[1]: https://github.com/python/cpython/blob/v3.7.3/Lib/pickletools.py#L820-L831

python pickle: Fix endianess of binfloat argument

---

network/ethernet_frame.ksy

As per request in https://github.com/kaitai-io/kaitai_struct_formats/issues/245, I've implemented simple support for 802.1Q structures in Ethernet frame.

Added 802.1Q implementation in Ethernet frame

---

network/udp_datagram.ksy

I propose to add padding to the `udp_datagram.ksy` since the `body` of `udp_datagram` is only of a specific length. Everything after the udp_datagram.body with size `length - 8` is actually no data.

add padding in udp_datagram.ksy

---

executable/te.ksy

From UEFI Platform Initialization spec document:
"The Terse Executable (TE) image format was created as a mechanism to reduce the overhead of the PE/COFF headers in PE32/PE32+ images, resulting in a corresponding reduction of image sizes for executables running in the PI Architecture environment. Reducing image size provides an opportunity for use of a smaller system flash part."
So the TE format is basically a stripped version of PE.
This type of executables could be found inside the UEFI firmware. The UEFI firmware is stored in SPI flash memory, which is a chip soldered on a system’s motherboard. UEFI firmware is very modular: it usually contains dozens, if not hundreds, of executables. To store all these separates files, the firmware is laid out in volumes using the Firmware File …

Adding Terse Executable file format

---

image/bmp.ksy

Current BMP spec in formats repository is somewhat rudimentary, it is not very much usable. I tried to improve that.
Every BMP file contains a DIB header (bitmap information header) part. There are several different variants. Every of them has a `header_size` field in the beginning, which is used for determining which header is present in the image. 
The existing implementation advised to switch over this field and select appropriate type representing the particular header. Although it seems to make sense, it complicates the access to common properties (e.g. width and height). To access width in the header, you would have to do this:
```yaml
instances:
image_width:
value: >-
len_dib_header == header_type::bitmap_core_header.to_i ?
header.dib_header.as<bitmap_core_header>.width : …
```

Extend BMP format support

---

serialization/python_pickle.ksy

This allows multiple pickles to be read from a single stream, or for a
stream to contain data following a pickle. It also flags invalid pickles
that lack a stop op.

pickle: Terminate ops sequence with stop opcode

---

network/dns_packet.ksy

Opcode defined after [RFC1035](https://www.ietf.org/rfc/rfc1035.txt) can have totally different structure, for instance DNS UPDATE

Do not attempt to parse unknown DNS packets

---

.github/workflows/main.yml
_build/Gemfile
_build/build-html
_build/format_base.html.erb
_build/format_lang.html.erb
_build/header.html.erb

It seems to me that the quality of the syntax highlighting provided by highlight.js that we use now is quite limited, one can see many highlighting issues across the whole format gallery. We use quite a limited subset of YAML actively for KSY purposes, and yet this library has various problems with that. For example https://formats.kaitai.io/utf8_string/index.html, this is not exactly how it should look like.
So I propose switching to Pygments, as we use for the documentation (https://github.com/kaitai-io/kaitai_struct_doc/pull/34). I think for https://doc.kaitai.io/ it works quite well.

Use Pygments syntax highlighter

---

network/rtpdump.ksy

Popular file format for RTP tools to replay streams (telephony, audio, video) from network capture.
http://www.cs.cmu.edu/~./libra-demo/rtptools-1.17/rtptools.html

Adding file format network/rtpdump

---

windows/windows_minidump.ksy

The enum `stream_types` for Windows minidumps was missing:
* a few official stream types from https://msdn.microsoft.com/en-us/library/ms680394(v=vs.85).aspx
* the stream types used for the Breakpad/Crashpad extensions
These two commits add them

windows_minidump: Add missing stream types to enum

---

executable/elf.ksy

- DT_ENCODING is not encoded into files, it's a special value used by tools.
REF: https://docs.oracle.com/cd/E19683-01/816-7529/chapter6-42444/index.html
- DT_LOOS and DT_HIOS
- DT_VALRNGLO and DT_VALRNGHI
- DT_ADDRRNGLO and DT_ADDRRNGHI
- DT_LOPROC and DT_HIPROC
These are not encoded into files, they're just hi/lo region values.
ref: https://docs.oracle.com/cd/E23824_01/html/819-0690/chapter6-42444.html
- DT_SUNW_RTLDINF is for internal use and not encoded into files.
ref: https://docs.oracle.com/cd/E23824_01/html/819-0690/chapter6-42444.html

fix duplicate enums in elf kaitai-io#279

---

filesystem/android_super.ksy

The metadata stored by Android at the beginning of a "super" partition, which is what it calls a disk partition that holds one or more Dynamic Partitions. Dynamic Partitions do more or less the same thing that LVM does on Linux, allowing Android to map ranges of non-contiguous extents to a single logical device. This metadata holds that mapping.
[sample.zip](https://github.com/kaitai-io/kaitai_struct_formats/files/5390627/sample.zip) contains a sample file (`super_truncated.img`) that I obtained by extracting only the header portion of a "super" partition provided as part of an official Android emulator image.

Add Android super.img (Dynamic Partitions) format

---

database/dbf.ksy

There is some disagreement in descriptions and the implementation:
```
0−10	Field name: a string from one to 10 characters of the "alnum" set and a terminating null character (HEX: 00), usually the extra space is filled with null characters.
```
From here: [https://ru.wikipedia.org/wiki/DBF#Описание_формата](https://ru.wikipedia.org/wiki/DBF#%D0%9E%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5_%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%82%D0%B0)
and
```
0–10	11 bytes	Field name in ASCII (zero-filled)
```
From here: https://en.wikipedia.org/wiki/.dbf#Field_descriptor_array
But, it happens that the rest is clogged with spaces, and they are striped when reading.
I didn't understand how to add this to the description...

DBF: field name ends with x\0

---

network/dime_message.ksy

Adding the old-school DIME (Direct Internet Message Encapsulation) format. Based on the 2002 Microsoft draft [here](http://xml.coverpages.org/draft-nielsen-dime-02.txt).
I was unsure on the folder where to put it, but settled on `network/`.
Thanks for this awesome project!

Added DIME message

---

archive/android_dto.ksy

Documentation: https://source.android.com/devices/architecture/dto/partitions
Reference implementation: https://android.googlesource.com/platform/system/libufdt/+/refs/heads/master/utils/
Test files (gunzip before testing):
[dtb-exynos9820.img.gz](https://github.com/kaitai-io/kaitai_struct_formats/files/5954481/dtb-exynos9820.img.gz)
[dtbo-G973F.img.gz](https://github.com/kaitai-io/kaitai_struct_formats/files/5954482/dtbo-G973F.img.gz)

Add android's DTB/DTBO partitions format

---

security/openpgp_message.ksy

The word "reserved" was used multiple times. Although the compiler compiles it just fine I ran into trouble when using it with Python. This commit should resolve this issue.

openpgp message: rewrite duplicate "reserved" entries

---

image/png.ksy

Animated PNG (APNG) is a not very widely used PNG format, but sometimes encountered in the wild. This PR adds support for the three chunks that are defined in the APNG specification:
https://wiki.mozilla.org/APNG_Specification
I have tested this with the Kaitai Web IDE and test files from:
http://littlesvr.ca/apng/

PNG: include definitions for animated PNG (APNG)

---

image/gif.ksy

This further processes application extensions as defined in section 26 of the GIF89a specification. Application extensions include things like animation, XMP data, and so on.

GIF: process application authentication (GIF89a specification section 26)

---

serialization/ruby_marshal.ksy

See https://docs.ruby-lang.org/en/2.4.0/marshal_rdoc.html#label-Object+References

ruby_marshal: add support for object link '@'

---

archive/mozilla_mar.ksy

A fairly simple description of the Mozilla ARchive format. This is not in widespread use. I have tested it with several files from the Mozilla FTP site as well as https://github.com/mozilla/build-mar/tree/master/tests

add Mozilla ARchive file format

---

hardware/edid.ksy

I explored https://en.wikipedia.org/wiki/Extended_Display_Identification_Data, fixed some issues and tested the result against a single EDID file.
`refresh_rate_mod` became `b6` because `u1` (`horiz_active_pixels_mod`) + `b2` (`aspect_ratio`) + `b6` (`refresh_rate_mod`) = `u2` as expected. Another evidence is that 123 - 60 = 63, and `b6` gives 2^6 = [0..63] in contrast to `b5` which gives 2^5 = [0..31].
If a standard timing equals to `01 01`, then it's marked as unused. It would be better to mark a whole `std_timing` as `null` in this case but I didn't find how to do that in http://doc.kaitai.io/ksy_diagram.html.

Fix edid.ksy

---

image/gimp_brush.ksy

This is a .ksy for version 2 of the GIMP brush file format

add .ksy for the GIMP brush file format

---

archive/android_asus_bootldr.ksy

This is a specification for the bootloader used on several ASUS Android devices. The magic is the same as some other Android bootloaders. I have only implemented support for version 2 and later, as I couldn't quickly find test files that use version 1 (and I am not even sure if any of those files were even publicly released).

add a specification for the bootloader used on several ASUS Android devices

---

network/rtp_packet.ksy

Including the payload type in each enumerated name e.g. `reserved19` for payload type 19, which is reserved in the RTP spec. Done for two reasons:
* logging/printing enumerated type variables will show the payload type
* finding the next free reserved/unassigned label is simpler and unambiguous
Fixes https://github.com/kaitai-io/kaitai_struct_formats/issues/498.

Include payload type in enum

---

executable/elf.ksy

Parse note sections in ELF files. The fields note_name and note_description are 4 byte aligned (hence the ugly calculation). Although the ELF specification seems to hint that the note_name field is ASCII I have found that this isn't the case on Linux binaries that have the .gnu.build.attributes section:
https://fedoraproject.org/wiki/Toolchain/Watermark#Proposed_Specification_for_non-loaded_notes
Fixes #253

ELF: parse note sections + other ELF edits

---

executable/mach_o.ksy

This is a code signature field new to iOS binaries as of early 2019 and new to macOS 12. It contains entitlements encoded as ASN.1 DER instead of XML. Also fix up an existing field name to better match Apple's XNU source code.
This contribution is on behalf of my company.

Mach-O: support DER-encoded entitlements

---

archive/xar.ksy
archive/xar_header.ksy

The XAR format is an archive that consists of a header, a zlib compressed XML document and then the payload. The structure of the payload (the files, etc.) is described in the XML file. Because Kaitai Struct does not have a built in XML parser this parser is limited to just the header.

add XAR header format

---

archive/android_bootldr_huawei.ksy
archive/android_img_huawei.ksy

This commit adds a parser for the Huawei Bootlader packed image format as found on some Android devices made by Huawei. Tested with files found in the OTA image for Nexus 6P.

add Huawei Bootloader packed image format

---

media/wav.ksy

This PR fixes a simple spelling mistakes and adds chunk names that are not in the standard spec, namely ID3 and PEAK. The data of these chunks is not yet processed any further.
Test files for ID3: https://github.com/alexa/alexa-auto-sdk/tree/3.1/samples/cpp/assets/inputs
Test files for PEAK: https://github.com/scipy/scipy/tree/master/scipy/io/tests/data

wav: fix spelling mistake, process more chunks

---

font/grub2_font.ksy
font/grub2font.ksy

This description adds support for the GRUB2 font file format. This does not yet process the character definitions itself.

add GRUB2 font description

---

archive/rpm.ksy

This is a fairly complete parser for version 3 of the RPM file format which is the currently maintained version of RPM. Other versions are either very old or are unmaintained and not covered by this specification.
There is some duplication in the format that cannot easily be removed )see https://github.com/kaitai-io/kaitai_struct/issues/872 ).
This doesn't parse the entire format. Specifically the following are not parsed or reported:
* the size of the payload. This is dependent on some values in the signature section of the RPM. I left notes about how I *think* it should be done and I would appreciate some comments there.
*  the individual tags are not split out further or given any meaning, as this about a few hundred tags that would potentially need to be processed. I think it is more …

add definition for RPM files

---

executable/microsoft_pe.ksy

- Rename enum certificate_entry.certificate_type to certificate_entry.certificate_type_enum to avoid name collision with sequence field certificat_entry.certificate_type
- Resolve compilation error in parser generated for csharp target

Resolve name collision

---

font/ttf.ksy

This fixes two bugs with parsing ttf files:
* parsing fonts with `maxp` version 0.5 tables
* reading `post` tables, where it was attempted to read data beyond the end of the stream

fix TTF parsing bugs

---

archive/rpm.ksy

RPM recently added loongarch64 as a supported architecture.

rpm: add loongarch64 to architectures

---

executable/dos_mz.ksy

This updates fixes the magic and reworks the header which also corrects the offsets of the body.
The previous version did not work for various executables used in FreeDOS 1.2 like `PING.EXE`. These are now correctly (or: "more correctly") parsed.
The biggest change is reworking the header and to look at the actual length of the header (for which a separate `len_header` instance was created). According to <http://www.delorie.com/djgpp/doc/exe/>:
```
The header includes the relocation entries.
```

DOS MZ updates

---

executable/java_class.ksy

I bumped into an error where when using a Python generated with the `.ksy` I would get an error: `"ConstantPoolEntry' object has no attribute 'tag'` for the second entry of entries that take up two entries (`long` and `double`).
The generated code looks like this:
```python
@property
def is_two_entries(self):
if hasattr(self, '_m_is_two_entries'):
return self._m_is_two_entries if hasattr(self, '_m_is_two_entries') else None
self._m_is_two_entries =  ((self.tag == JavaClass.ConstantPoolEntry.TagEnum.long) or (self.tag == JavaClass.ConstantPoolEntry.TagEnum.double)) 
return self._m_is_two_entries if hasattr(self, '_m_is_two_entries') else None
```
The problem here is that it tries to find `self.tag` which doesn't exist for these "second entries":
```python
def _read(self):
if not …
```

java_class: improve is_two_entries to prevent 'ConstantPoolEntry' object has no attribute 'tag' error in generated Python code

---

executable/elf.ksy

elf: sync with upstream binutils code, particularly:
https://gitlab.com/gnutools/binutils-gdb/-/commit/dd207c1302d28d2d2b33cff058bb3fbf5138b480
https://gitlab.com/gnutools/binutils-gdb/-/commit/a7fd11862703e45d2774981a4888bc127d473b06

elf: sync with upstream binutils code

---

executable/java_class.ksy

Mach-O files have the same magic bytes. This PR adds a sanity check to avoid false positives.

java_class: add sanity check for the version number

---

executable/android_nanoapp_header.ksy
executable/napp_header.ksy

This adds a description of the Google nano app header, a file sometimes seen in Android devices using the Context Hun Runtime Environment (CHRE) <https://source.android.com/devices/contexthub>.
Test files can be found inside the `vendor.img` file of this recent Android 12L factory image: <https://dl.google.com/dl/android/aosp/oriole-sp2a.220405.004-factory-f560807e.zip>

add the Android Nano app header

---

archive/zisofs.ksy

This PR adds a specification for zisofs compressed files. I have put it in `archive` as I think that this might be the best place, as it processes a single file that has been compressed with `mkzftree`. That being said, I could imagine it being conceptually belonging to `filesystem`, so if you want to move it, go ahead.
<http://fileformats.archiveteam.org/wiki/Zisofs>

zisofs: add specification

---

executable/mach_o.ksy
executable/mach_o_fat.ksy

Multiarch Mach-Os use a special "fat" container format. Currently, we recognize the magic for this in `mach_o.ksy` but then just try to parse it like a normal Mach-O, which fails. Since fat Mach-Os can't be nested inside themselves, I believe that a separate `ksy` to parse them is the correct approach. This PR adds such a `ksy`, which imports the existing Mach-O parser to parse each architecture.
This contribution is on behalf of my company.

Add mach_o_fat format for multiarch Mach-O objects

---

archive/rpm.ksy

This commit adds some of the new RPM tags that were added in the past 6 months.

rpm: add new tags 5099/5100/5101/5102

---

macos/ds_store.ksy

This PR fixes an issue related to some array index type conversions in Java.
See https://github.com/kaitai-io/kaitai_struct/issues/956 for further information.

ds_store: fix array index type issue in some target languages

---

macos/ds_store.ksy

Hi,
Missing parentheses in the `.DS_Store` file description cause wrong computation of block sizes.
I was quite surprised to find this bug, as everything worked well when I submitted the file description to the format gallery years ago. I tried to reproduce the setup I used at that time (Kaitai Struct compiler and runtime in version 0.8, etc.), but in vain. Just like if the bug has always been there. Anyway, this PR fixes the issue.
You can find sample files for testing in my original PR (https://github.com/kaitai-io/kaitai_struct_formats/pull/131).
Thanks.

DS_Store - Fix block size computation

---

network/pcap.ksy

Some new link types were added at https://www.tcpdump.org/linktypes.html

pcap: add new link types

---

common/dos_datetime.ksy
executable/microsoft_pe.ksy
image/bmp.ksy
image/ico.ksy
log/windows_evt_log.ksy
media/avi.ksy
network/dime_message.ksy
network/microsoft_network_monitor_v2.ksy
serialization/asn1/asn1_der.ksy
serialization/ruby_marshal.ksy
windows/windows_minidump.ksy
windows/windows_resource_file.ksy
windows/windows_systemtime.ksy

Microsoft now redirects `docs.microsoft.com` there and can eventually retire the old domain somewhen.

Replace `docs.microsoft.com` with `learn.microsoft.com`

---

game/renderware_binary_stream.ksy

Atomic is commonly the top level section in DFF files. This makes geometry is parsable in many older RenderWare game files.

games/renderware_binary_stream: add atomic struct definition

---

image/pif.ksy

This PR adds a fairly basic specification of the PIF format, a fairly new image format for embedded systems and microcontrollers: https://hackaday.com/2022/05/08/creating-an-image-format-for-embedded-hardware/

add Portable Image Format (pif)

---

game/renderware_binary_stream.ksy

This fixed a TODO and makes the last non-working files work from older Data Design Interactive Ltd games load perfectly.

game/renderware_binary_stream: add support for multiple uv layers

---

filesystem/amlogic_emmc_partitions.ksy

This is an unnamed and undocumented partition table format implemented by the bootloader and kernel that Amlogic provides for their Linux SoCs (Meson series at least, and probably others). They appear to use this rather than GPT, the industry standard, because their BootROM loads and executes the next stage loader from offset 512 (`0x200`) on the eMMC, which is exactly where the GPT header would have to start. So instead of changing their BootROM, Amlogic devised this partition table, which lives at an offset of 36MiB (`0x240_0000`) on the eMMC and so doesn't conflict. This parser expects as input just the partition table from that offset. The maximum number of partitions in a table is 32, which corresponds to a maximum table size of 1304 bytes (`0x518`). …

Add Amlogic eMMC partition format, as used by Meson SoCs

---

game/minecraft_nbt.ksy

The Minecraft Fandom wiki has been forked to a new domain: minecraft.wiki. Learn more here: https://minecraft.wiki/w/Minecraft_Wiki:Moving_from_Fandom. This PR updates all URLs accordingly.

Update Minecraft wiki links to new domain

---

executable/elf.ksy

when I compile `elf.ksy` I get a load of warnings about the naming of `program_header_entry_size`, `section_header_entry_size`, `qty_program_header`, `qty_section_header`
this PR renames those fields to fix the warnings (to match what's in the style guide)

elf: fix naming warnings

---

log/glibc_utmp.ksy

The type of tv_sec in bits/utmp.h of GNU libc was changed from int32_t to __uint32_t on 19 April 2024 to address the year 2038 problem.
The relevant commit of GNU libc:
https://sourceware.org/git/?p=glibc.git;a=commit;h=5361ad3910c257bc327567be76fde532ed238e42

Change the type of timeval.sec of log/glibc_utmp.ksy to follow the change of GNU libc

---

log/glibc_utmp.ksy

utmp.h of GNU libc defines the type of ut_pid as pid_t (signed int). The current definition of pid in the glibc_utmp.ksy is u4 (unsigned int). This commit corrects the type of pid to s4 (signed int).
The relevant definitions in GNU libc:
ut_pid is defined as pid_t
https://sourceware.org/git/?p=glibc.git;a=blob;f=bits/utmp.h;h=d9a166e8d685af5c3603d1e0d64d08786d5a42ed;hb=HEAD
__PID_T_TYPE is defined as __S32_TYPE
https://sourceware.org/git/?p=glibc.git;a=blob;f=bits/typesizes.h;h=b6db5c3637702a760f8318881342f7c327ed3fe0;hb=HEAD

Correct the type of pid of log/glibc_utmp.ksy to match the definition in GNU libc
